#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RoundedImageView.Resource", IsApplication=false)]

namespace RoundedImageView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000d
			public static int BorderColor = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public static int BorderWidth = 2130771980;
			
			// aapt resource value: 0x7f010007
			public static int CornerRadius = 2130771975;
			
			// aapt resource value: 0x7f01000a
			public static int CornerRadiusBottomLeft = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public static int CornerRadiusBottomRight = 2130771979;
			
			// aapt resource value: 0x7f010008
			public static int CornerRadiusTopLeft = 2130771976;
			
			// aapt resource value: 0x7f010009
			public static int CornerRadiusTopRight = 2130771977;
			
			// aapt resource value: 0x7f01000e
			public static int MutateBackground = 2130771982;
			
			// aapt resource value: 0x7f010000
			public static int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public static int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public static int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public static int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public static int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public static int MvxTemplate = 2130771970;
			
			// aapt resource value: 0x7f01000f
			public static int Oval = 2130771983;
			
			// aapt resource value: 0x7f010010
			public static int TileMode = 2130771984;
			
			// aapt resource value: 0x7f010011
			public static int TileModeX = 2130771985;
			
			// aapt resource value: 0x7f010012
			public static int TileModeY = 2130771986;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f020000
			public static int MvvmCrossTagId = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int MvxBindingTagUnique = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int clamp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int mirror = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int repeat = 2130837508;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public static int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public static int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public static int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public static int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public static int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public static int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public static int MvxListView_MvxItemTemplate = 0;
			
			public static int[] RoundedImageView = new int[] {
					16843037,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 7
			public static int RoundedImageView_BorderColor = 7;
			
			// aapt resource value: 6
			public static int RoundedImageView_BorderWidth = 6;
			
			// aapt resource value: 1
			public static int RoundedImageView_CornerRadius = 1;
			
			// aapt resource value: 4
			public static int RoundedImageView_CornerRadiusBottomLeft = 4;
			
			// aapt resource value: 5
			public static int RoundedImageView_CornerRadiusBottomRight = 5;
			
			// aapt resource value: 2
			public static int RoundedImageView_CornerRadiusTopLeft = 2;
			
			// aapt resource value: 3
			public static int RoundedImageView_CornerRadiusTopRight = 3;
			
			// aapt resource value: 8
			public static int RoundedImageView_MutateBackground = 8;
			
			// aapt resource value: 9
			public static int RoundedImageView_Oval = 9;
			
			// aapt resource value: 10
			public static int RoundedImageView_TileMode = 10;
			
			// aapt resource value: 11
			public static int RoundedImageView_TileModeX = 11;
			
			// aapt resource value: 12
			public static int RoundedImageView_TileModeY = 12;
			
			// aapt resource value: 0
			public static int RoundedImageView_android_scaleType = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
